#Librerias

In [ ]:
import pandas as pd
import os

# Librerías de manipulación de datos
import pandas as pd
import numpy as np

# Opciones de Pandas
pd.set_option('display.max_columns', None)

# Librerías de visualización
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from IPython.display import display
import plotly.express as px

# Librerías para estadística y pruebas
import scipy.stats as stats
from scipy.stats import gaussian_kde, kstest, norm, shapiro
import statsmodels.api as sm
from statsmodels.formula.api import ols

# Librerías de machine learning y preprocesamiento
from sklearn.ensemble import IsolationForest
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

# Librerías para métricas de modelos
from sklearn.model_selection import train_test_split, GridSearchCV
import statsmodels.api as sm
from sklearn.metrics import mean_squared_error,  mean_absolute_error, mean_absolute_percentage_error, r2_score, classification_report
import math

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, ConfusionMatrixDisplay,f1_score, precision_score, recall_score, roc_auc_score, roc_curve

#Carga de datos

In [ ]:
os.environ['KAGGLE_CONFIG_DIR'] = '.'

In [ ]:
!kaggle competitions download -c udea-ai-4-eng-20252-pruebas-saber-pro-colombia

Warning: Your Kaggle API key is readable by other users on this system! To fix this, you can run 'chmod 600 ./kaggle.json'
Downloading udea-ai-4-eng-20252-pruebas-saber-pro-colombia.zip to /content
  0% 0.00/29.9M [00:00<?, ?B/s]
100% 29.9M/29.9M [00:00<00:00, 2.29GB/s]

In [ ]:
!unzip udea-ai-4-eng-20252-pruebas-saber-pro-colombia

Archive:  udea-ai-4-eng-20252-pruebas-saber-pro-colombia.zip
  inflating: submission_example.csv
  inflating: test.csv
  inflating: train.csv

In [ ]:
df_train=pd.read_csv('train.csv')

In [ ]:
df_train.head()

,ID,PERIODO_ACADEMICO,E_PRGM_ACADEMICO,E_PRGM_DEPARTAMENTO,E_VALORMATRICULAUNIVERSIDAD,E_HORASSEMANATRABAJA,F_ESTRATOVIVIENDA,F_TIENEINTERNET,F_EDUCACIONPADRE,F_TIENELAVADORA,F_TIENEAUTOMOVIL,E_PRIVADO_LIBERTAD,E_PAGOMATRICULAPROPIO,F_TIENECOMPUTADOR,F_TIENEINTERNET.1,F_EDUCACIONMADRE,RENDIMIENTO_GLOBAL,INDICADOR_1,INDICADOR_2,INDICADOR_3,INDICADOR_4
0,904256,20212,ENFERMERIA,BOGOTÁ,Entre 5.5 millones y menos de 7 millones,Menos de 10 horas,Estrato 3,Si,Técnica o tecnológica incompleta,Si,Si,N,No,Si,Si,Postgrado,medio-alto,0.322,0.208,0.310,0.267
1,645256,20212,DERECHO,ATLANTICO,Entre 2.5 millones y menos de 4 millones,0,Estrato 3,No,Técnica o tecnológica completa,Si,No,N,No,Si,No,Técnica o tecnológica incompleta,bajo,0.311,0.215,0.292,0.264
2,308367,20203,MERCADEO Y PUBLICIDAD,BOGOTÁ,Entre 2.5 millones y menos de 4 millones,Más de 30 horas,Estrato 3,Si,Secundaria (Bachillerato) completa,Si,No,N,No,No,Si,Secundaria (Bachillerato) completa,bajo,0.297,0.214,0.305,0.264
3,470353,20195,ADMINISTRACION DE EMPRESAS,SANTANDER,Entre 4 millones y menos de 5.5 millones,0,Estrato 4,Si,No sabe,Si,No,N,No,Si,Si,Secundaria (Bachillerato) completa,alto,0.485,0.172,0.252,0.190
4,989032,20212,PSICOLOGIA,ANTIOQUIA,Entre 2.5 millones y menos de 4 millones,Entre 21 y 30 horas,Estrato 3,Si,Primaria completa,Si,Si,N,No,Si,Si,Primaria completa,medio-bajo,0.316,0.232,0.285,0.294

In [ ]:
df_test=pd.read_csv('test.csv')
df_test.head()

,ID,PERIODO_ACADEMICO,E_PRGM_ACADEMICO,E_PRGM_DEPARTAMENTO,E_VALORMATRICULAUNIVERSIDAD,E_HORASSEMANATRABAJA,F_ESTRATOVIVIENDA,F_TIENEINTERNET,F_EDUCACIONPADRE,F_TIENELAVADORA,F_TIENEAUTOMOVIL,E_PRIVADO_LIBERTAD,E_PAGOMATRICULAPROPIO,F_TIENECOMPUTADOR,F_TIENEINTERNET.1,F_EDUCACIONMADRE,INDICADOR_1,INDICADOR_2,INDICADOR_3,INDICADOR_4
0,550236,20183,TRABAJO SOCIAL,BOLIVAR,Menos de 500 mil,Menos de 10 horas,Estrato 3,Si,Técnica o tecnológica completa,Si,No,N,Si,Si,Si,Primaria completa,0.328,0.219,0.317,0.247
1,98545,20203,ADMINISTRACION COMERCIAL Y DE MERCADEO,ANTIOQUIA,Entre 2.5 millones y menos de 4 millones,Entre 21 y 30 horas,Estrato 2,Si,Secundaria (Bachillerato) completa,Si,No,N,No,Si,Si,Técnica o tecnológica completa,0.227,0.283,0.296,0.324
2,499179,20212,INGENIERIA MECATRONICA,BOGOTÁ,Entre 1 millón y menos de 2.5 millones,0,Estrato 3,Si,Secundaria (Bachillerato) incompleta,Si,No,N,No,Si,Si,Secundaria (Bachillerato) completa,0.285,0.228,0.294,0.247
3,782980,20195,CONTADURIA PUBLICA,SUCRE,Entre 1 millón y menos de 2.5 millones,Entre 21 y 30 horas,Estrato 1,No,Primaria incompleta,Si,No,N,No,No,No,Primaria incompleta,0.160,0.408,0.217,0.294
4,785185,20212,ADMINISTRACION DE EMPRESAS,ATLANTICO,Entre 2.5 millones y menos de 4 millones,Entre 11 y 20 horas,Estrato 2,Si,Secundaria (Bachillerato) completa,Si,No,N,No,Si,Si,Secundaria (Bachillerato) completa,0.209,0.283,0.306,0.286

#Preprocesamiento para train

## Datos faltantes

En el análisis exploratorio se encontró que el dataset de entrenamiento está conformado por 692500 filas y 21 columnas (variables). El dataset no tiene columnas repetidas con el mismo nombre pero si tiene repetida la columna "F_TIENEINTERNET" como "F_TIENEINTERNET.1" esto debido a que ambas columnas tienen la misma cantidad de datos con SI y NO y tambien la misma cantidad de faltantes. No tiene filas duplicadas pero si tiene datos faltantes; entre las columnas con mayor proporción de faltantes se encuentran 'F_TIENEAUTOMOVIL', 'F_TIENELAVADORA' y 'F_TIENE COMPUTADOR' que representan más del 50% de los faltantes otras como 'E_VALORMATRICULAUNIVERSIDAD' y 'E_PAGOMATRICULAPROPIO' no representan ni el 1% de los faltantes. Se modificaron los tipos de datos para 'ID' y para 'PERIODO_ACADEMICO' puesto que estas variables aunque sean números están expresando categorías. El dataset solo tiene 4 variables númericas que son 'INDICADOR_1', 'INDICADOR_2', 'INDICADOR_3', 'INDICADOR_4'.

In [ ]:
df_train= df_train.drop(columns=['F_TIENEINTERNET.1'],  errors='ignore') #Eliminación de columna repetida

In [ ]:
df_train['ID']=df_train['ID'].astype('object')
df_train['PERIODO_ACADEMICO']=df_train['PERIODO_ACADEMICO'].astype('object')

Algunas variables no son ordinales como:

'F_TIENEINTERNET','F_TIENELAVADORA','F_TIENEAUTOMOVIL','F_TIENECOMPUTADOR','E_PAGOMATRICULAPROPIO',

es decir, sus categorias no representan un orden, los valores faltantes de estas serán reemplazados con la categoria 'otro'. La variable 'F_ESTRATOVIVIENDA' tiene una categoria llamada 'Sin Estrato' aquí se añadirán todos los valores faltantes de dicha variable. Las variables restantes serán tratadas posteriormente luego de convertirlas a categoricas para ayudar al modelo a interpretar la ordinalidad de cada una.

In [ ]:
for col in ['F_TIENEINTERNET', 'F_TIENELAVADORA', 'F_TIENEAUTOMOVIL', 'F_TIENECOMPUTADOR','E_PAGOMATRICULAPROPIO']:
    df_train[col] = df_train[col].fillna('otro')

In [ ]:
df_train['F_ESTRATOVIVIENDA']=df_train['F_ESTRATOVIVIENDA'].fillna('Sin Estrato')

In [ ]:
df_train = df_train.drop(columns=['ID'], errors='ignore')

In [ ]:
df_train['E_VALORMATRICULAUNIVERSIDAD']=df_train['E_VALORMATRICULAUNIVERSIDAD'].fillna(df_train['E_VALORMATRICULAUNIVERSIDAD'].mode())

In [ ]:
moda_padre = df_train['F_EDUCACIONPADRE'].mode()[0]
moda_madre = df_train['F_EDUCACIONMADRE'].mode()[0]

df_train['F_EDUCACIONPADRE']=df_train['F_EDUCACIONPADRE'].fillna(moda_padre)
df_train['F_EDUCACIONMADRE']=df_train['F_EDUCACIONMADRE'].fillna(moda_madre)

In [ ]:
moda_horas = df_train['E_HORASSEMANATRABAJA'].mode()[0]
df_train['E_HORASSEMANATRABAJA']=df_train['E_HORASSEMANATRABAJA'].fillna(moda_horas)

## Feature engineering

### Creación de variables

**CATEGORIA_PROGRAMA**

Esta variable agrupa los distintos programas académicos (más de 900 originalmente) en categorías temáticas o áreas de conocimiento, como Ingenierías, Ciencias Sociales, Administración y Economía, Educación, Ciencias de la Salud, Artes y Comunicación, entre otras. Su objetivo es representar el campo disciplinar de formación del estudiante sin perder información relevante, pero reduciendo la alta cardinalidad original. Esto facilita al modelo identificar patrones de desempeño por área académica.

In [ ]:
def categorizar_programa(x):
    x = str(x).upper()

    if any(word in x for word in ['INGENIER', 'SISTEMAS', 'SOFTWARE', 'COMPUTACIÓN', 'ELECTR', 'INDUSTRIAL', 'CIVIL', 'MECANIC', 'TECNOLOG','ARQUI','COMPU','URBAN','CONSTR','OCEANO','DISENO']):
        return 'INGENIERÍAS Y CIENCIAS APLICADAS'
    elif any(word in x for word in ['MEDIC', 'ENFERM', 'SALUD', 'FISIOTERAP', 'BIOQUIM', 'NUTRIC', 'ODONTO','INTRU','INSTRU','BACTER','MICROB','OPTO','TERAPIA','FONO','FARMACE','FARMA','ENFERM','VETERIN']):
        return 'CIENCIAS DE LA SALUD'
    elif any(word in x for word in ['SOCIOLOG', 'PSICOLOG', 'FILOSOF', 'HISTOR', 'ANTROPOLOG', 'TEOLOG', 'BIBLIC', 'POLITIC', 'GOBIERNO','DERECHO','TRABAJO','POLÍTICA','PSICÓLOGA','INTERNACIONALES','JURIS','ARQUEO','ARCHI','GERONT']):
        return 'CIENCIAS SOCIALES Y HUMANAS'
    elif any(word in x for word in ['ADMINISTR', 'ECONOM', 'NEGOC', 'FINANZ', 'COMERC', 'EMPRES', 'MARKETING', 'GERENCIA','CONTAD']):
        return 'ADMINISTRACIÓN Y ECONOMÍA'
    elif any(word in x for word in ['LICENCIAT', 'PEDAGOG', 'DOCEN', 'EDUCAC', 'ENSEÑAN','TRADUCC','LINGUISTICA']):
        return 'EDUCACIÓN'
    elif any(word in x for word in ['MATEM', 'FISIC', 'QUIMIC', 'BIOLOG', 'GEOLOG', 'ECOLOG', 'ASTRONOM','FÍSICA','QUÍMICA','ESTADISTICA','ESTADÍSTICA','ZOO']):
        return 'CIENCIAS EXACTAS Y NATURALES'
    elif any(word in x for word in ['ARTE', 'MUSICA', 'TEATRO', 'CINE', 'DISEÑ', 'PUBLICID', 'COMUNIC', 'LITERAT', 'FILOL', 'LENGUA','MÚSICA','DANZA','BANDA','LITERARIA','LITERARIOS','FOTOGRAFÍA','AUDIOVISUALES','PRODUCCIÓN','ANIMACIÓN','CULTURAL']):
        return 'ARTES, COMUNICACIÓN Y HUMANIDADES'
    elif any(word in x for word in ['TURIS', 'HOTEL', 'GASTRON', 'CULINAR']):
        return 'TURISMO Y HOTELERÍA'
    elif any(word in x for word in ['CRIMINAL', 'INVESTIGAC', 'POLIC', 'MILITAR', 'NAVA', 'SEGURIDAD']):
        return 'CRIMINALÍSTICA Y SEGURIDAD'
    elif any(word in x for word in ['DEPORTE', 'DEPORTIVO','DEPORTIVA']):
        return 'DEPORTE'
    elif any(word in x for word in ['MERCADEO', 'MERCADOLOGIA','PLANEACION']):
        return 'NEGOCIOS Y MERCADEO'
    else:
        return 'OTRAS'

# Aplicar la función
df_train['CATEGORIA_PROGRAMA'] = df_train['E_PRGM_ACADEMICO'].apply(categorizar_programa)

In [ ]:
df_train['CATEGORIA_PROGRAMA'].unique()

array(['CIENCIAS DE LA SALUD', 'CIENCIAS SOCIALES Y HUMANAS',
       'ARTES, COMUNICACIÓN Y HUMANIDADES', 'ADMINISTRACIÓN Y ECONOMÍA',
       'INGENIERÍAS Y CIENCIAS APLICADAS', 'TURISMO Y HOTELERÍA',
       'EDUCACIÓN', 'CIENCIAS EXACTAS Y NATURALES', 'DEPORTE',
       'NEGOCIOS Y MERCADEO', 'CRIMINALÍSTICA Y SEGURIDAD', 'OTRAS'],
      dtype=object)

**AÑO**

Esta variable representa el año de presentación o cohorte académica del estudiante, extraído del campo PERIODO_ACADEMICO. Captura el componente temporal del dataset y permite observar posibles tendencias o cambios en el desempeño a lo largo del tiempo, relacionados con políticas educativas, reformas curriculares o variaciones en la cobertura del examen

In [ ]:
df_train['AÑO'] = df_train['PERIODO_ACADEMICO'].astype(str).str[:4].astype(int)

## Eliminación de variables

In [ ]:
df_clean=df_train.copy()

In [ ]:
cols_drop = [
    'PERIODO_ACADEMICO',
    'E_PRGM_ACADEMICO',
    'F_ESTRATOVIVIENDA',
    'E_PRIVADO_LIBERTAD',
    'E_PAGOMATRICULAPROPIO',
]
df_model = df_clean.drop(columns=cols_drop, errors='ignore')

In [ ]:
df_model_2 = pd.get_dummies(df_model, columns=['CATEGORIA_PROGRAMA', 'E_PRGM_DEPARTAMENTO','AÑO','E_VALORMATRICULAUNIVERSIDAD','E_HORASSEMANATRABAJA','F_TIENEINTERNET','F_EDUCACIONPADRE',
                                               'F_TIENELAVADORA','F_TIENEAUTOMOVIL','F_TIENECOMPUTADOR','F_EDUCACIONMADRE'], drop_first=True,dtype=int)

In [ ]:
from sklearn.preprocessing import StandardScaler

# Columnas numéricas a escalar
num_cols = ['INDICADOR_1','INDICADOR_2','INDICADOR_3','INDICADOR_4']

scaler = StandardScaler()
df_model_2[num_cols] = scaler.fit_transform(df_model_2[num_cols])

In [ ]:
from sklearn.preprocessing import LabelEncoder
# Definición del orden correcto
mapeo_ordenado = {
    'alto': 0,
    'medio-alto': 1,
    'medio-bajo': 2,
    'bajo': 3
}
df_model_2['RENDIMIENTO_GLOBAL_encoded'] = df_model_2['RENDIMIENTO_GLOBAL'].map(mapeo_ordenado)

#Preprocesamiento para test

## Datos faltantes

Se evalua que el conjunto de datos para test tenga las mismas variables y los mismos faltantes que el conjunto de datos de train para aplicar el mismo preprocesamiento

In [ ]:
def visual_check(df):

    print('Shape:\n',df.shape,'\n')

    print('Data Types:\n', df.dtypes,'\n\n')

    df_colum_duplicated=df.columns.duplicated()
    print("Columnas duplicadas:\n",df_colum_duplicated,'\n\n')

    df_fil_duplicated=df.duplicated()
    print("Filas duplicadas:\n",df_fil_duplicated,'\n\n')

    df_colum_faltantes=df.columns[df.isnull().any()]
    print("Datos faltantes por columnas:\n",df_colum_faltantes,'\n\n')

    display(df.describe().T)

visual_check(df_test)

Shape:
 (296786, 20)

Data Types:
 ID                               int64
PERIODO_ACADEMICO                int64
E_PRGM_ACADEMICO                object
E_PRGM_DEPARTAMENTO             object
E_VALORMATRICULAUNIVERSIDAD     object
E_HORASSEMANATRABAJA            object
F_ESTRATOVIVIENDA               object
F_TIENEINTERNET                 object
F_EDUCACIONPADRE                object
F_TIENELAVADORA                 object
F_TIENEAUTOMOVIL                object
E_PRIVADO_LIBERTAD              object
E_PAGOMATRICULAPROPIO           object
F_TIENECOMPUTADOR               object
F_TIENEINTERNET.1               object
F_EDUCACIONMADRE                object
INDICADOR_1                    float64
INDICADOR_2                    float64
INDICADOR_3                    float64
INDICADOR_4                    float64
dtype: object


Columnas duplicadas:
 [False False False False False False False False False False False False
 False False False False False False False False]


Filas duplicadas:
 0         False
1         False
2         False
3         False
4         False
          ...
296781    False
296782    False
296783    False
296784    False
296785    False
Length: 296786, dtype: bool


Datos faltantes por columnas:
 Index(['E_VALORMATRICULAUNIVERSIDAD', 'E_HORASSEMANATRABAJA',
       'F_ESTRATOVIVIENDA', 'F_TIENEINTERNET', 'F_EDUCACIONPADRE',
       'F_TIENELAVADORA', 'F_TIENEAUTOMOVIL', 'E_PAGOMATRICULAPROPIO',
       'F_TIENECOMPUTADOR', 'F_TIENEINTERNET.1', 'F_EDUCACIONMADRE'],
      dtype='object')

,count,mean,std,min,25%,50%,75%,max
ID,296786.0,494730.695238,285576.351746,2.0,247318.250,494808.500,742441.000,989285.000
PERIODO_ACADEMICO,296786.0,20198.379078,10.525743,20183.0,20195.000,20195.000,20203.000,20213.000
INDICADOR_1,296786.0,0.268235,0.121352,0.0,0.205,0.242,0.312,0.663
INDICADOR_2,296786.0,0.259989,0.094596,0.0,0.214,0.269,0.306,0.484
INDICADOR_3,296786.0,0.262855,0.059635,0.0,0.254,0.278,0.295,0.322
INDICADOR_4,296786.0,0.262450,0.067587,0.0,0.253,0.284,0.302,0.331

In [ ]:
# Seleccionar solo las columnas de interés
cols = [
    'E_VALORMATRICULAUNIVERSIDAD', 'E_HORASSEMANATRABAJA',
       'F_ESTRATOVIVIENDA', 'F_TIENEINTERNET', 'F_EDUCACIONPADRE',
       'F_TIENELAVADORA', 'F_TIENEAUTOMOVIL', 'E_PAGOMATRICULAPROPIO',
       'F_TIENECOMPUTADOR', 'F_TIENEINTERNET.1', 'F_EDUCACIONMADRE'
]

# Crear dataset de faltantes
faltantes_df = pd.DataFrame({
    "Columna": cols,
    "Faltantes": df_test[cols].isnull().sum().values,
    "Porcentaje (%)": (df_test[cols].isnull().mean().values * 100).round(2)
})

faltantes_df

                        Columna  Faltantes  Porcentaje (%)
0   E_VALORMATRICULAUNIVERSIDAD       2723            0.92
1          E_HORASSEMANATRABAJA      13379            4.51
2             F_ESTRATOVIVIENDA      13795            4.65
3               F_TIENEINTERNET      11539            3.89
4              F_EDUCACIONPADRE       9993            3.37
5               F_TIENELAVADORA      17259            5.82
6              F_TIENEAUTOMOVIL      18918            6.37
7         E_PAGOMATRICULAPROPIO       2807            0.95
8             F_TIENECOMPUTADOR      16439            5.54
9             F_TIENEINTERNET.1      11539            3.89
10             F_EDUCACIONMADRE      10223            3.44

Como tenemos las mismas variables con datos faltantes, aplicamos los mismos métodos de preprocesamiento y creamos las mismas nuevas variables creadas en test

In [ ]:
df_test= df_test.drop(columns=['F_TIENEINTERNET.1'],  errors='ignore') #Eliminación de columna repetida

In [ ]:
df_test['ID']=df_test['ID'].astype('object')
df_test['PERIODO_ACADEMICO']=df_test['PERIODO_ACADEMICO'].astype('object')

In [ ]:
for col in ['F_TIENEINTERNET', 'F_TIENELAVADORA', 'F_TIENEAUTOMOVIL', 'F_TIENECOMPUTADOR','E_PAGOMATRICULAPROPIO']:
    df_test[col] = df_test[col].fillna('otro')

In [ ]:
df_test['F_ESTRATOVIVIENDA']=df_test['F_ESTRATOVIVIENDA'].fillna('Sin Estrato')

In [ ]:
df_test = df_test.drop(columns=['ID'], errors='ignore')

In [ ]:
df_test['E_VALORMATRICULAUNIVERSIDAD']=df_test['E_VALORMATRICULAUNIVERSIDAD'].fillna(df_test['E_VALORMATRICULAUNIVERSIDAD'].mode())

In [ ]:
moda_padre = df_test['F_EDUCACIONPADRE'].mode()[0]
moda_madre = df_test['F_EDUCACIONMADRE'].mode()[0]

df_test['F_EDUCACIONPADRE']=df_test['F_EDUCACIONPADRE'].fillna(moda_padre)
df_test['F_EDUCACIONMADRE']=df_test['F_EDUCACIONMADRE'].fillna(moda_madre)

In [ ]:
moda_horas = df_test['E_HORASSEMANATRABAJA'].mode()[0]
df_test['E_HORASSEMANATRABAJA']=df_test['E_HORASSEMANATRABAJA'].fillna(moda_horas)

## Feature engineering

### Creación de variables

**CATEGORIA_PROGRAMA**

Esta variable agrupa los distintos programas académicos (más de 900 originalmente) en categorías temáticas o áreas de conocimiento, como Ingenierías, Ciencias Sociales, Administración y Economía, Educación, Ciencias de la Salud, Artes y Comunicación, entre otras. Su objetivo es representar el campo disciplinar de formación del estudiante sin perder información relevante, pero reduciendo la alta cardinalidad original. Esto facilita al modelo identificar patrones de desempeño por área académica.

In [ ]:
def categorizar_programa(x):
    x = str(x).upper()

    if any(word in x for word in ['INGENIER', 'SISTEMAS', 'SOFTWARE', 'COMPUTACIÓN', 'ELECTR', 'INDUSTRIAL', 'CIVIL', 'MECANIC', 'TECNOLOG','ARQUI','COMPU','URBAN','CONSTR','OCEANO','DISENO']):
        return 'INGENIERÍAS Y CIENCIAS APLICADAS'
    elif any(word in x for word in ['MEDIC', 'ENFERM', 'SALUD', 'FISIOTERAP', 'BIOQUIM', 'NUTRIC', 'ODONTO','INTRU','INSTRU','BACTER','MICROB','OPTO','TERAPIA','FONO','FARMACE','FARMA','ENFERM','VETERIN']):
        return 'CIENCIAS DE LA SALUD'
    elif any(word in x for word in ['SOCIOLOG', 'PSICOLOG', 'FILOSOF', 'HISTOR', 'ANTROPOLOG', 'TEOLOG', 'BIBLIC', 'POLITIC', 'GOBIERNO','DERECHO','TRABAJO','POLÍTICA','PSICÓLOGA','INTERNACIONALES','JURIS','ARQUEO','ARCHI','GERONT']):
        return 'CIENCIAS SOCIALES Y HUMANAS'
    elif any(word in x for word in ['ADMINISTR', 'ECONOM', 'NEGOC', 'FINANZ', 'COMERC', 'EMPRES', 'MARKETING', 'GERENCIA','CONTAD']):
        return 'ADMINISTRACIÓN Y ECONOMÍA'
    elif any(word in x for word in ['LICENCIAT', 'PEDAGOG', 'DOCEN', 'EDUCAC', 'ENSEÑAN','TRADUCC','LINGUISTICA']):
        return 'EDUCACIÓN'
    elif any(word in x for word in ['MATEM', 'FISIC', 'QUIMIC', 'BIOLOG', 'GEOLOG', 'ECOLOG', 'ASTRONOM','FÍSICA','QUÍMICA','ESTADISTICA','ESTADÍSTICA','ZOO']):
        return 'CIENCIAS EXACTAS Y NATURALES'
    elif any(word in x for word in ['ARTE', 'MUSICA', 'TEATRO', 'CINE', 'DISEÑ', 'PUBLICID', 'COMUNIC', 'LITERAT', 'FILOL', 'LENGUA','MÚSICA','DANZA','BANDA','LITERARIA','LITERARIOS','FOTOGRAFÍA','AUDIOVISUALES','PRODUCCIÓN','ANIMACIÓN','CULTURAL']):
        return 'ARTES, COMUNICACIÓN Y HUMANIDADES'
    elif any(word in x for word in ['TURIS', 'HOTEL', 'GASTRON', 'CULINAR']):
        return 'TURISMO Y HOTELERÍA'
    elif any(word in x for word in ['CRIMINAL', 'INVESTIGAC', 'POLIC', 'MILITAR', 'NAVA', 'SEGURIDAD']):
        return 'CRIMINALÍSTICA Y SEGURIDAD'
    elif any(word in x for word in ['DEPORTE', 'DEPORTIVO','DEPORTIVA']):
        return 'DEPORTE'
    elif any(word in x for word in ['MERCADEO', 'MERCADOLOGIA','PLANEACION']):
        return 'NEGOCIOS Y MERCADEO'
    else:
        return 'OTRAS'

# Aplicar la función
df_test['CATEGORIA_PROGRAMA'] = df_test['E_PRGM_ACADEMICO'].apply(categorizar_programa)

In [ ]:
df_test['CATEGORIA_PROGRAMA'].unique()

array(['CIENCIAS SOCIALES Y HUMANAS', 'ADMINISTRACIÓN Y ECONOMÍA',
       'INGENIERÍAS Y CIENCIAS APLICADAS', 'CIENCIAS DE LA SALUD',
       'EDUCACIÓN', 'CRIMINALÍSTICA Y SEGURIDAD',
       'ARTES, COMUNICACIÓN Y HUMANIDADES', 'OTRAS',
       'NEGOCIOS Y MERCADEO', 'CIENCIAS EXACTAS Y NATURALES', 'DEPORTE',
       'TURISMO Y HOTELERÍA'], dtype=object)

**AÑO**

Esta variable representa el año de presentación o cohorte académica del estudiante, extraído del campo PERIODO_ACADEMICO. Captura el componente temporal del dataset y permite observar posibles tendencias o cambios en el desempeño a lo largo del tiempo, relacionados con políticas educativas, reformas curriculares o variaciones en la cobertura del examen

In [ ]:
df_test['AÑO'] = df_test['PERIODO_ACADEMICO'].astype(str).str[:4].astype(int)

## Eliminación de variables

In [ ]:
df_test_model=df_test.copy()

In [ ]:
cols_drop = [
    'PERIODO_ACADEMICO',
    'E_PRGM_ACADEMICO',
    'F_ESTRATOVIVIENDA',
    'E_PRIVADO_LIBERTAD',
    'E_PAGOMATRICULAPROPIO'
]
df_test_model = df_test_model.drop(columns=cols_drop, errors='ignore')

In [ ]:
df_test_model = pd.get_dummies(df_test_model, columns=['CATEGORIA_PROGRAMA', 'E_PRGM_DEPARTAMENTO','AÑO','E_VALORMATRICULAUNIVERSIDAD','E_HORASSEMANATRABAJA','F_TIENEINTERNET','F_EDUCACIONPADRE',
                                               'F_TIENELAVADORA','F_TIENEAUTOMOVIL','F_TIENECOMPUTADOR','F_EDUCACIONMADRE'], drop_first=True,dtype=int)

In [ ]:
from sklearn.preprocessing import StandardScaler

# Columnas numéricas a escalar
num_cols = ['INDICADOR_1','INDICADOR_2','INDICADOR_3','INDICADOR_4']

scaler = StandardScaler()
df_test_model[num_cols] = scaler.fit_transform(df_test_model[num_cols])

#Creación de dataframe para modelos

In [ ]:
# Definir las columnas a excluir (la variable target y su versión original)
drop_columns = ['RENDIMIENTO_GLOBAL', 'RENDIMIENTO_GLOBAL_encoded']

# 1. Conjunto de ENTRENAMIENTO
# X_train contiene todas las features de df_model_2, sin la target.
x_train = df_model_2.drop(columns=drop_columns)
# y_train contiene la variable target codificada.
y_train = df_model_2['RENDIMIENTO_GLOBAL_encoded']

# 2. Conjunto de PRUEBA (Base: df_test_model)
x_final_test = df_test_model.copy()

In [ ]:
print("--- Resumen de los DataFrames ---")
print(f"Dimensiones de x_train: {x_train.shape}")
print(f"Dimensiones de x_final_test (sin y_test): {x_final_test.shape}")

--- Resumen de los DataFrames ---
Dimensiones de x_train: (692500, 89)
Dimensiones de x_final_test (sin y_test): (296786, 89)

Para este modelo se inició con un preprocesado simple, solo se rellenaron valores faltantes, se crearon las variables de 'CATEGORIA_PROGRAMA' explicada anteriormente y 'AÑO'. Se aplicará inicialmente un modelo simple de regresión logistica para testear la métrica y se espera mejorarla con modelos mas potentes

#Modelo de regresión logistica

In [ ]:
#Creacion del modelo de regresion logistica y los modelos de prediccion

model = LogisticRegression(max_iter=200) # definir el modelo
model.fit(x_train,y_train) # entrenar el modelo

y_pred_train = model.predict(x_train) # guardar la predicción para train
y_pred_test = model.predict(x_test) # guardar la predicción para test

In [ ]:
y_pred_train

In [ ]:
y_pred_test

array([2, 2, 3, ..., 3, 3, 3])

In [ ]:
# y_test: Etiquetas reales
# y_pred: Predicciones del modelo
print(f"Accuracy: {accuracy_score(y_train, y_pred_train)}")

# Estas funciones ya están optimizadas para multiclase
print(f"Precisión (Macro): {precision_score(y_train, y_pred_train, average='macro')}")
print(f"Recall (Macro): {recall_score(y_train, y_pred_train, average='macro')}")
print(f"F1-score (Macro): {f1_score(y_train, y_pred_train, average='macro')}")

Accuracy: 0.4084259927797834
Precisión (Macro): 0.3897918695797613
Recall (Macro): 0.40711563168457776
F1-score (Macro): 0.3913900208879285

Obtuvimos un accuracy (la metrica más relevante en este caso) de 0.40, lo que quiere decir que del total de datos acertó en un 40% (esto con los datos de entrenamiento)